/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nothanks;

/**
 *
 * @author user
 */
public class FivePlayerGameGUI extends javax.swing.JFrame {

    /**
     * Creates new form FivePlayerGameGUI
     */
    public FivePlayerGameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jChipLabel2 = new javax.swing.JLabel();
        jPlayerChipTotal = new javax.swing.JLabel();
        jCurrentPlayerLeftButton = new javax.swing.JButton();
        jCurrentPlayerCardLabel1 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel2 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel3 = new javax.swing.JLabel();
        jCurrentPlayerRightButton = new javax.swing.JButton();
        jGiveUpButton = new javax.swing.JButton();
        jRightPlayerDownButton = new javax.swing.JButton();
        jRightPlayerCardLabel2 = new javax.swing.JLabel();
        jRightPlayerCardLabel1 = new javax.swing.JLabel();
        jRightPlayerUpButton = new javax.swing.JButton();
        jTopRightPlayerRightButton = new javax.swing.JButton();
        jTopRightPlayerCardLable2 = new javax.swing.JLabel();
        jTopRIghtPlayerCardLabel1 = new javax.swing.JLabel();
        jTopRightPlayerLeftButton = new javax.swing.JButton();
        jTopLeftPlayerRightButton = new javax.swing.JButton();
        jTopLeftPlayerLeftButton = new javax.swing.JButton();
        jTopLeftPlayerCardLabel1 = new javax.swing.JLabel();
        jTopLeftPlayerCardLabel2 = new javax.swing.JLabel();
        jLeftPlayerDownButton = new javax.swing.JButton();
        jLeftPlayerUpButton = new javax.swing.JButton();
        jLeftPlayerCardLabel1 = new javax.swing.JLabel();
        jLeftPlayerCardLabel2 = new javax.swing.JLabel();
        jTopLeftPlayerName = new javax.swing.JLabel();
        jTopRightPlayerName = new javax.swing.JLabel();
        jCurrentPlayerName = new javax.swing.JLabel();
        jLeftPlayerName = new javax.swing.JLabel();
        jRightPlayerName = new javax.swing.JLabel();
        jDeckLabel = new javax.swing.JLabel();
        jRevealedCardLabel = new javax.swing.JLabel();
        jChipLabel1 = new javax.swing.JLabel();
        jChipsOnCardLabel = new javax.swing.JLabel();
        jTakeCardButton = new javax.swing.JButton();
        jPlaceChipButton = new javax.swing.JButton();
        jBackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChipLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        jPlayerChipTotal.setText("Player chip total");
        jLayeredPane1.add(jPlayerChipTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 20));

        jCurrentPlayerLeftButton.setText("<- Next");
        jLayeredPane1.add(jCurrentPlayerLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 80, -1));
        jLayeredPane1.add(jCurrentPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 60, 110));
        jLayeredPane1.add(jCurrentPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 60, 110));
        jLayeredPane1.add(jCurrentPlayerCardLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 70, 110));

        jCurrentPlayerRightButton.setText("Next ->");
        jLayeredPane1.add(jCurrentPlayerRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 80, -1));

        jGiveUpButton.setText("Give up");
        jLayeredPane1.add(jGiveUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, -1, -1));

        jRightPlayerDownButton.setText("v");
        jLayeredPane1.add(jRightPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 40, -1));
        jLayeredPane1.add(jRightPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 60, 100));
        jLayeredPane1.add(jRightPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 60, 110));

        jRightPlayerUpButton.setText("^");
        jLayeredPane1.add(jRightPlayerUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 40, -1));

        jTopRightPlayerRightButton.setText(">");
        jLayeredPane1.add(jTopRightPlayerRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 40, -1));
        jLayeredPane1.add(jTopRightPlayerCardLable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 60, 110));
        jLayeredPane1.add(jTopRIghtPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 70, 110));

        jTopRightPlayerLeftButton.setText("<");
        jLayeredPane1.add(jTopRightPlayerLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 40, -1));

        jTopLeftPlayerRightButton.setText(">");
        jLayeredPane1.add(jTopLeftPlayerRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 40, -1));

        jTopLeftPlayerLeftButton.setText("<");
        jLayeredPane1.add(jTopLeftPlayerLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, -1));
        jLayeredPane1.add(jTopLeftPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 110));
        jLayeredPane1.add(jTopLeftPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, 110));

        jLeftPlayerDownButton.setText("v");
        jLayeredPane1.add(jLeftPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 40, -1));

        jLeftPlayerUpButton.setText("^");
        jLayeredPane1.add(jLeftPlayerUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, -1));
        jLayeredPane1.add(jLeftPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, 110));
        jLayeredPane1.add(jLeftPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 70, 110));

        jTopLeftPlayerName.setText("Top left player name");
        jLayeredPane1.add(jTopLeftPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jTopRightPlayerName.setText("Top right player name");
        jLayeredPane1.add(jTopRightPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jCurrentPlayerName.setText("Current player name");
        jLayeredPane1.add(jCurrentPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jLeftPlayerName.setText("Left Player Name");
        jLayeredPane1.add(jLeftPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jRightPlayerName.setText("Right Player name");
        jLayeredPane1.add(jRightPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, -1, -1));

        jDeckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_back.jpg"))); // NOI18N
        jLayeredPane1.add(jDeckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));
        jLayeredPane1.add(jRevealedCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 70, 110));

        jChipLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));
        jLayeredPane1.add(jChipsOnCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jTakeCardButton.setText("Take card");
        jLayeredPane1.add(jTakeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jPlaceChipButton.setText("Place chip");
        jLayeredPane1.add(jPlaceChipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5PlayerBackground.png"))); // NOI18N
        jLayeredPane1.add(jBackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FivePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FivePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FivePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FivePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FivePlayerGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackgroundLabel;
    private javax.swing.JLabel jChipLabel1;
    private javax.swing.JLabel jChipLabel2;
    private javax.swing.JLabel jChipsOnCardLabel;
    private javax.swing.JLabel jCurrentPlayerCardLabel1;
    private javax.swing.JLabel jCurrentPlayerCardLabel2;
    private javax.swing.JLabel jCurrentPlayerCardLabel3;
    private javax.swing.JButton jCurrentPlayerLeftButton;
    private javax.swing.JLabel jCurrentPlayerName;
    private javax.swing.JButton jCurrentPlayerRightButton;
    private javax.swing.JLabel jDeckLabel;
    private javax.swing.JButton jGiveUpButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLeftPlayerCardLabel1;
    private javax.swing.JLabel jLeftPlayerCardLabel2;
    private javax.swing.JButton jLeftPlayerDownButton;
    private javax.swing.JLabel jLeftPlayerName;
    private javax.swing.JButton jLeftPlayerUpButton;
    private javax.swing.JButton jPlaceChipButton;
    private javax.swing.JLabel jPlayerChipTotal;
    private javax.swing.JLabel jRevealedCardLabel;
    private javax.swing.JLabel jRightPlayerCardLabel1;
    private javax.swing.JLabel jRightPlayerCardLabel2;
    private javax.swing.JButton jRightPlayerDownButton;
    private javax.swing.JLabel jRightPlayerName;
    private javax.swing.JButton jRightPlayerUpButton;
    private javax.swing.JButton jTakeCardButton;
    private javax.swing.JLabel jTopLeftPlayerCardLabel1;
    private javax.swing.JLabel jTopLeftPlayerCardLabel2;
    private javax.swing.JButton jTopLeftPlayerLeftButton;
    private javax.swing.JLabel jTopLeftPlayerName;
    private javax.swing.JButton jTopLeftPlayerRightButton;
    private javax.swing.JLabel jTopRIghtPlayerCardLabel1;
    private javax.swing.JLabel jTopRightPlayerCardLable2;
    private javax.swing.JButton jTopRightPlayerLeftButton;
    private javax.swing.JLabel jTopRightPlayerName;
    private javax.swing.JButton jTopRightPlayerRightButton;
    // End of variables declaration//GEN-END:variables
}
