/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nothanks;

/**
 *
 * @author user
 */
public class FourPlayerGameGUI extends javax.swing.JFrame {

    /**
     * Creates new form FourPlayerGameGUI
     */
    public FourPlayerGameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jCurrentPlayerCardLable1 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel2 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel3 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel4 = new javax.swing.JLabel();
        jCurrentPlayerCardLable5 = new javax.swing.JLabel();
        jCurrentPlayerRightButton = new javax.swing.JButton();
        jCurrentPlayerLeftButton = new javax.swing.JButton();
        jLeftPlayerCardLabel1 = new javax.swing.JLabel();
        jLeftPlayerCardLabel2 = new javax.swing.JLabel();
        jLeftPlayerDownButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRightPlayerCardLabel1 = new javax.swing.JLabel();
        jRightPlayerCardLabel2 = new javax.swing.JLabel();
        jRightPlayerDownButton = new javax.swing.JButton();
        jRightPlayerUpButton = new javax.swing.JButton();
        jTopPlayerCardLabel1 = new javax.swing.JLabel();
        jTopPlayerCardLabel2 = new javax.swing.JLabel();
        jTopPlayerCardLabel3 = new javax.swing.JLabel();
        jTopPlayerRightButton = new javax.swing.JButton();
        jTopPlayerLeftButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jChipsOnCardLabel = new javax.swing.JLabel();
        jChipLabel1 = new javax.swing.JLabel();
        jRevealedCardLabel = new javax.swing.JLabel();
        jRightPlayerName = new javax.swing.JLabel();
        jLeftPlayerName = new javax.swing.JLabel();
        jTopPlayerName = new javax.swing.JLabel();
        jCurrentPlayerName = new javax.swing.JLabel();
        jTakeCardButton = new javax.swing.JButton();
        jPlaceChipButton = new javax.swing.JButton();
        jChipLabel2 = new javax.swing.JLabel();
        jGiveUpButton = new javax.swing.JButton();
        jPlayerChipTotalLabel = new javax.swing.JLabel();
        jBackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jCurrentPlayerCardLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 80, 100));
        jLayeredPane1.add(jCurrentPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 70, 100));
        jLayeredPane1.add(jCurrentPlayerCardLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 70, 110));
        jLayeredPane1.add(jCurrentPlayerCardLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 70, 110));
        jLayeredPane1.add(jCurrentPlayerCardLable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 70, 100));

        jCurrentPlayerRightButton.setText("Next ->");
        jLayeredPane1.add(jCurrentPlayerRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, -1, -1));

        jCurrentPlayerLeftButton.setText("<- Next");
        jLayeredPane1.add(jCurrentPlayerLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));
        jLayeredPane1.add(jLeftPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, 110));
        jLayeredPane1.add(jLeftPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 110));

        jLeftPlayerDownButton.setText("v");
        jLayeredPane1.add(jLeftPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 40, -1));

        jButton4.setText("^");
        jLayeredPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 40, -1));
        jLayeredPane1.add(jRightPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 70, 110));
        jLayeredPane1.add(jRightPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 60, 110));

        jRightPlayerDownButton.setText("v");
        jLayeredPane1.add(jRightPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 40, -1));

        jRightPlayerUpButton.setText("^");
        jLayeredPane1.add(jRightPlayerUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 40, -1));
        jLayeredPane1.add(jTopPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 110));
        jLayeredPane1.add(jTopPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 110));
        jLayeredPane1.add(jTopPlayerCardLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 70, 110));

        jTopPlayerRightButton.setText(">");
        jLayeredPane1.add(jTopPlayerRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 40, -1));

        jTopPlayerLeftButton.setText("<");
        jLayeredPane1.add(jTopPlayerLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_back.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));
        jLayeredPane1.add(jChipsOnCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jChipLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));
        jLayeredPane1.add(jRevealedCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 70, 100));

        jRightPlayerName.setText("Right player name");
        jLayeredPane1.add(jRightPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        jLeftPlayerName.setText("Left player name");
        jLayeredPane1.add(jLeftPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jTopPlayerName.setText("Top player name");
        jLayeredPane1.add(jTopPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jCurrentPlayerName.setText("Current player name");
        jLayeredPane1.add(jCurrentPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jTakeCardButton.setText("Take card");
        jLayeredPane1.add(jTakeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jPlaceChipButton.setText("Place chip");
        jLayeredPane1.add(jPlaceChipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jChipLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jGiveUpButton.setText("Give up");
        jLayeredPane1.add(jGiveUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, -1, -1));

        jPlayerChipTotalLabel.setText("Player chip total");
        jLayeredPane1.add(jPlayerChipTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        jBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4PlayerBackground.png"))); // NOI18N
        jLayeredPane1.add(jBackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourPlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourPlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourPlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourPlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourPlayerGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackgroundLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jChipLabel1;
    private javax.swing.JLabel jChipLabel2;
    private javax.swing.JLabel jChipsOnCardLabel;
    private javax.swing.JLabel jCurrentPlayerCardLabel2;
    private javax.swing.JLabel jCurrentPlayerCardLabel3;
    private javax.swing.JLabel jCurrentPlayerCardLabel4;
    private javax.swing.JLabel jCurrentPlayerCardLable1;
    private javax.swing.JLabel jCurrentPlayerCardLable5;
    private javax.swing.JButton jCurrentPlayerLeftButton;
    private javax.swing.JLabel jCurrentPlayerName;
    private javax.swing.JButton jCurrentPlayerRightButton;
    private javax.swing.JButton jGiveUpButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLeftPlayerCardLabel1;
    private javax.swing.JLabel jLeftPlayerCardLabel2;
    private javax.swing.JButton jLeftPlayerDownButton;
    private javax.swing.JLabel jLeftPlayerName;
    private javax.swing.JButton jPlaceChipButton;
    private javax.swing.JLabel jPlayerChipTotalLabel;
    private javax.swing.JLabel jRevealedCardLabel;
    private javax.swing.JLabel jRightPlayerCardLabel1;
    private javax.swing.JLabel jRightPlayerCardLabel2;
    private javax.swing.JButton jRightPlayerDownButton;
    private javax.swing.JLabel jRightPlayerName;
    private javax.swing.JButton jRightPlayerUpButton;
    private javax.swing.JButton jTakeCardButton;
    private javax.swing.JLabel jTopPlayerCardLabel1;
    private javax.swing.JLabel jTopPlayerCardLabel2;
    private javax.swing.JLabel jTopPlayerCardLabel3;
    private javax.swing.JButton jTopPlayerLeftButton;
    private javax.swing.JLabel jTopPlayerName;
    private javax.swing.JButton jTopPlayerRightButton;
    // End of variables declaration//GEN-END:variables
}
