/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nothanks;

/**
 *
 * @author user
 */
public class ThreePlayerGameGUI extends javax.swing.JFrame {

    /**
     * Creates new form ThreePlayerGameGUI
     */
    public ThreePlayerGameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jCurrentPlayerCardLabel1 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel2 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel3 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel4 = new javax.swing.JLabel();
        jCurrentPlayerCardLabel5 = new javax.swing.JLabel();
        jDeckLabel = new javax.swing.JLabel();
        jRevealedCardLabel = new javax.swing.JLabel();
        jChipLabel1 = new javax.swing.JLabel();
        jChipsOnCardLabel = new javax.swing.JLabel();
        jLeftPlayerCardLabel1 = new javax.swing.JLabel();
        jLeftPlayerCardLabel2 = new javax.swing.JLabel();
        jLeftPlayerCardLabel3 = new javax.swing.JLabel();
        jCurrentLeftButton = new javax.swing.JButton();
        jCurrentRightButton = new javax.swing.JButton();
        jRightPlayerUpButton = new javax.swing.JButton();
        jRightPlayerDownButton = new javax.swing.JButton();
        jLeftPlayerUpButton = new javax.swing.JButton();
        jLeftPlayerDownButton = new javax.swing.JButton();
        jRightPlayerCardLabel1 = new javax.swing.JLabel();
        jRightPlayerCardLabel2 = new javax.swing.JLabel();
        jRightPlayerLabel3 = new javax.swing.JLabel();
        jCurrentPlayerName = new javax.swing.JLabel();
        jLeftPlayerName = new javax.swing.JLabel();
        jRightPlayerName = new javax.swing.JLabel();
        jTakeCardButton = new javax.swing.JButton();
        jPlaceChipButton = new javax.swing.JButton();
        jChipLabel2 = new javax.swing.JLabel();
        jGiveUpButton = new javax.swing.JButton();
        jPlayerChipTotalLabel = new javax.swing.JLabel();
        jBackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jCurrentPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 70, 110));
        jLayeredPane1.add(jCurrentPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 70, 100));
        jLayeredPane1.add(jCurrentPlayerCardLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 70, 100));
        jLayeredPane1.add(jCurrentPlayerCardLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 70, 100));
        jLayeredPane1.add(jCurrentPlayerCardLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 70, 100));

        jDeckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_back.jpg"))); // NOI18N
        jLayeredPane1.add(jDeckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));
        jLayeredPane1.add(jRevealedCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 70, 110));

        jChipLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jChipsOnCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(jChipsOnCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 60, 20));
        jLayeredPane1.add(jLeftPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 110));
        jLayeredPane1.add(jLeftPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 70, 110));
        jLayeredPane1.add(jLeftPlayerCardLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 60, 110));

        jCurrentLeftButton.setText("<- Next");
        jLayeredPane1.add(jCurrentLeftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        jCurrentRightButton.setText("Next ->");
        jLayeredPane1.add(jCurrentRightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        jRightPlayerUpButton.setText("^");
        jLayeredPane1.add(jRightPlayerUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 30, 20));

        jRightPlayerDownButton.setText("v");
        jLayeredPane1.add(jRightPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 30, 20));

        jLeftPlayerUpButton.setText("^");
        jLayeredPane1.add(jLeftPlayerUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, -1));

        jLeftPlayerDownButton.setText("v");
        jLayeredPane1.add(jLeftPlayerDownButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 40, -1));
        jLayeredPane1.add(jRightPlayerCardLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 70, 110));
        jLayeredPane1.add(jRightPlayerCardLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 60, 110));
        jLayeredPane1.add(jRightPlayerLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 60, 110));

        jCurrentPlayerName.setText("Current player name");
        jLayeredPane1.add(jCurrentPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        jLeftPlayerName.setText("Left player name");
        jLayeredPane1.add(jLeftPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jRightPlayerName.setText("Right player name");
        jLayeredPane1.add(jRightPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 20));

        jTakeCardButton.setText("Take card");
        jLayeredPane1.add(jTakeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jPlaceChipButton.setText("Place chip");
        jLayeredPane1.add(jPlaceChipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jChipLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_Chip.png"))); // NOI18N
        jLayeredPane1.add(jChipLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jGiveUpButton.setText("Give up");
        jLayeredPane1.add(jGiveUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, -1, -1));

        jPlayerChipTotalLabel.setText("Player chip total");
        jLayeredPane1.add(jPlayerChipTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3PlayerBackground.png"))); // NOI18N
        jLayeredPane1.add(jBackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreePlayerGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreePlayerGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackgroundLabel;
    private javax.swing.JLabel jChipLabel1;
    private javax.swing.JLabel jChipLabel2;
    private javax.swing.JLabel jChipsOnCardLabel;
    private javax.swing.JButton jCurrentLeftButton;
    private javax.swing.JLabel jCurrentPlayerCardLabel1;
    private javax.swing.JLabel jCurrentPlayerCardLabel2;
    private javax.swing.JLabel jCurrentPlayerCardLabel3;
    private javax.swing.JLabel jCurrentPlayerCardLabel4;
    private javax.swing.JLabel jCurrentPlayerCardLabel5;
    private javax.swing.JLabel jCurrentPlayerName;
    private javax.swing.JButton jCurrentRightButton;
    private javax.swing.JLabel jDeckLabel;
    private javax.swing.JButton jGiveUpButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLeftPlayerCardLabel1;
    private javax.swing.JLabel jLeftPlayerCardLabel2;
    private javax.swing.JLabel jLeftPlayerCardLabel3;
    private javax.swing.JButton jLeftPlayerDownButton;
    private javax.swing.JLabel jLeftPlayerName;
    private javax.swing.JButton jLeftPlayerUpButton;
    private javax.swing.JButton jPlaceChipButton;
    private javax.swing.JLabel jPlayerChipTotalLabel;
    private javax.swing.JLabel jRevealedCardLabel;
    private javax.swing.JLabel jRightPlayerCardLabel1;
    private javax.swing.JLabel jRightPlayerCardLabel2;
    private javax.swing.JButton jRightPlayerDownButton;
    private javax.swing.JLabel jRightPlayerLabel3;
    private javax.swing.JLabel jRightPlayerName;
    private javax.swing.JButton jRightPlayerUpButton;
    private javax.swing.JButton jTakeCardButton;
    // End of variables declaration//GEN-END:variables
}
